name = "MixedModelsSim"
uuid = "d5ae56c5-23ca-4a1f-b505-9fc4796fc1fe"
authors = ["Phillip Alday", "Douglas Bates", "Shravan Vasishth", "Reinhold Kliegl"]
version = "0.1.0"

[deps]
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
