name = "MixedModelsSim"
uuid = "d5ae56c5-23ca-4a1f-b505-9fc4796fc1fe"
authors = ["Phillip Alday", "Douglas Bates", "Shravan Vasishth", "Reinhold Kliegl"]
version = "0.1.0"

[deps]
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.2"
