name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/*'
  release:
    types:
      - created
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
    actions: write
    contents: read
jobs:
  tier1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tier2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1.6, nightly]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
