name: Documenter
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches:
      - main
  workflow_dispatch:
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
    actions: write
    contents: read
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: 1
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
